const northcodersProfiles = {}

const tutorNames = ['Sam', 'Mitch', 'JD', 'Anat', 'Sally', 'Paul'];

// Sam
northcodersProfiles[1] = {
    "Adventurousness": 0.3,
    "Artistic interests": 0.9,
    "Emotionality": 0.5,
    "Imagination": 0.7,
    "Intellect": 0.2,
    "Authority-challenging": 0.8,
    "Achievement striving": 0.4,
    "Cautiousness": 0.2,
    "Dutifulness": 0.2,
    "Orderliness": 0.1,
    "Self-discipline": 1.0,
    "Self-efficacy": 0.7,
    "Activity level": 0.2,
    "Assertiveness": 0.95,
    "Cheerfulness": 0.9,
    "Excitement-seeking": 0.7,
    "Outgoing": 0.8,
    "Gregariousness": 0.5,
    "Altruism": 0.9,
    "Cooperation": 0.3,
    "Modesty": 0.1,
    "Uncompromising": 0.8,
    "Sympathy": 0.35,
    "Trust": 0.4,
    "Fiery": 0.7,
    "Prone to worry": 0.6,
    "Melancholy": 0.2,
    "Immoderation": 0.0,
    "Self-consciousness": 0.1,
    "Susceptible to stress": 0.9
}

// Mitch
northcodersProfiles[2] = {
    "Adventurousness": 0.2,
    "Artistic interests": 0.6,
    "Emotionality": 1,
    "Imagination": 0.1,
    "Intellect": 0.25,
    "Authority-challenging": 0.4,
    "Achievement striving": 0.8,
    "Cautiousness": 0.9,
    "Dutifulness": 0.8,
    "Orderliness": 0.7,
    "Self-discipline": 0.4,
    "Self-efficacy": 0.8,
    "Activity level": 0.55,
    "Assertiveness": 0.35,
    "Cheerfulness": 0.0,
    "Excitement-seeking": 0.1,
    "Outgoing": 0.2,
    "Gregariousness": 0.2,
    "Altruism": 0.9,
    "Cooperation": 0.29,
    "Modesty": 0.8,
    "Uncompromising": 0.35,
    "Sympathy": 0.1,
    "Trust": 0.9,
    "Fiery": 1.0,
    "Prone to worry": 0.55,
    "Melancholy": 0.4,
    "Immoderation": 0.8,
    "Self-consciousness": 0.5,
    "Susceptible to stress": 0.4
}

// JD
northcodersProfiles[3] = {
    "Adventurousness": 0.2,
    "Artistic interests": 0.3,
    "Emotionality": 0.1,
    "Imagination": 0.1,
    "Intellect": 0.7,
    "Authority-challenging": 0.7,
    "Achievement striving": 0.6,
    "Cautiousness": 0.9,
    "Dutifulness": 0.8,
    "Orderliness": 0.8,
    "Self-discipline": 0.8,
    "Self-efficacy": 0.8,
    "Activity level": 0.5,
    "Assertiveness": 0.2,
    "Cheerfulness": 0.3,
    "Excitement-seeking": 0.1,
    "Outgoing": 0.3,
    "Gregariousness": 0.3,
    "Altruism": 0.5,
    "Cooperation": 0.35,
    "Modesty": 0.9,
    "Uncompromising": 0.,
    "Sympathy": 0.1,
    "Trust": 0.9,
    "Fiery": 0.2,
    "Prone to worry": 0.2,
    "Melancholy": 0.8,
    "Immoderation": 0.8,
    "Self-consciousness": 0.2,
    "Susceptible to stress": 0.2
}

// Anat
northcodersProfiles[4] = {
    "Adventurousness": 0.9,
    "Artistic interests": 0.7,
    "Emotionality": 0.3,
    "Imagination": 8.5,
    "Intellect": 0.85,
    "Authority-challenging": 0.1,
    "Achievement striving": 0.85,
    "Cautiousness": 0.8,
    "Dutifulness": 0.5,
    "Orderliness": 0.3,
    "Self-discipline": 0.4,
    "Self-efficacy": 0.8,
    "Activity level": 0.4,
    "Assertiveness": 0.23,
    "Cheerfulness": 1.0,
    "Excitement-seeking": 0.1,
    "Outgoing": 0.2,
    "Gregariousness": 0.2,
    "Altruism": 0.6,
    "Cooperation": 0.5,
    "Modesty": 0.75,
    "Uncompromising": 0.5,
    "Sympathy": 0.1,
    "Trust": 0.63,
    "Fiery": 0.1,
    "Prone to worry": 0.57,
    "Melancholy": 0.15,
    "Immoderation": 0.77,
    "Self-consciousness": 0.5,
    "Susceptible to stress": 0.4
}

// Sally
northcodersProfiles[5] = {
    "Adventurousness": 0.1,
    "Artistic interests": 0.4,
    "Emotionality": 0.6,
    "Imagination": 0.6,
    "Intellect": 0.9,
    "Authority-challenging": 0.3,
    "Achievement striving": 0.9,
    "Cautiousness": 0.5,
    "Dutifulness": 0.9,
    "Orderliness": 0.4,
    "Self-discipline": 0.8,
    "Self-efficacy": 1,
    "Activity level": 0.7,
    "Assertiveness": 0.1,
    "Cheerfulness": 0.7,
    "Excitement-seeking": 0.05,
    "Outgoing": 0.4,
    "Gregariousness": 0.1,
    "Altruism": 0.8,
    "Cooperation": 0.8,
    "Modesty": 0.95,
    "Uncompromising": 0.3,
    "Sympathy": 0.95,
    "Trust": 0.8,
    "Fiery": 0,
    "Prone to worry": 0.3,
    "Melancholy": 0.2,
    "Immoderation": 0.1,
    "Self-consciousness": 0.8,
    "Susceptible to stress": 0.3
}

northcodersProfiles[6] = {
    "Adventurousness": 1,
    "Artistic interests": 0.05,
    "Emotionality": 0.5,
    "Imagination": 0.05,
    "Intellect": 0.2,
    "Authority-challenging": 0.1,
    "Achievement striving": 0.7,
    "Cautiousness": 0.0,
    "Dutifulness": 0.4,
    "Orderliness": 0.2,
    "Self-discipline": 0.1,
    "Self-efficacy": 0.8,
    "Activity level": 1,
    "Assertiveness": 0.2,
    "Cheerfulness": 1,
    "Excitement-seeking": 1,
    "Outgoing": 1,
    "Gregariousness": 0.8,
    "Altruism": 0.3,
    "Cooperation": 0.1,
    "Modesty": 0.2,
    "Uncompromising": 0.6,
    "Sympathy": 0.2,
    "Trust": 0.4,
    "Fiery": 0.3,
    "Prone to worry": 0.1,
    "Melancholy": 0.1,
    "Immoderation": 0.7,
    "Self-consciousness": 0.3,
    "Susceptible to stress": 0.15
}

module.exports = { northcodersProfiles, tutorNames }