const northcodersProfiles = {}

// Sam
northcodersProfiles[1] = {
    "Adventurousness": 0.3,
    "Artistic interests": 0.9,
    "Emotionality": 0.5,
    "Imagination": 0.7,
    "Intellect": 0.2,
    "Authority-challenging": 0.8,
    "Achievement striving": 0.4,
    "Cautiousness": 0.2,
    "Dutifulness": 0.2,
    "Orderliness": 0.1,
    "Self-discipline": 1.0,
    "Self-efficacy": 0.7,
    "Activity level": 0.2,
    "Assertiveness": 0.95,
    "Cheerfulness": 0.9,
    "Excitement-seeking": 0.7,
    "Outgoing": 0.8,
    "Gregariousness": 0.5,
    "Altruism": 0.9,
    "Cooperation": 0.3,
    "Modesty": 0.1,
    "Uncompromising": 0.8,
    "Sympathy": 0.35,
    "Trust": 0.4,
    "Fiery": 0.7,
    "Prone to worry": 0.6,
    "Melancholy": 0.2,
    "Immoderation": 0.0,
    "Self-consciousness": 0.1,
    "Susceptible to stress": 0.9
}

// Mitch
northcodersProfiles[2] = {
    "Adventurousness": 0.2,
    "Artistic interests": 0.6,
    "Emotionality": 1,
    "Imagination": 0.1,
    "Intellect": 0.25,
    "Authority-challenging": 0.4,
    "Achievement striving": 0.8,
    "Cautiousness": 0.9,
    "Dutifulness": 0.8,
    "Orderliness": 0.7,
    "Self-discipline": 0.4,
    "Self-efficacy": 0.8,
    "Activity level": 0.55,
    "Assertiveness": 0.35,
    "Cheerfulness": 0.0,
    "Excitement-seeking": 0.1,
    "Outgoing": 0.2,
    "Gregariousness": 0.2,
    "Altruism": 0.9,
    "Cooperation": 0.29,
    "Modesty": 0.8,
    "Uncompromising": 0.35,
    "Sympathy": 0.1,
    "Trust": 0.9,
    "Fiery": 1.0,
    "Prone to worry": 0.55,
    "Melancholy": 0.4,
    "Immoderation": 0.8,
    "Self-consciousness": 0.5,
    "Susceptible to stress": 0.4
}

module.exports = northcodersProfiles